# Workflow derived from https://github.com/posit-dev/r-shinylive/tree/actions-v1/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# Basic example of a GitHub Actions workflow that builds a Shiny app and deploys
# it to GitHub Pages.
name: Deploy app to gh-pages
on:
  # Manually trigger the workflow
  workflow_dispatch:
  # Trigger on push to main branch
  push:
    branches: ["main"]
  # Trigger on pull request to all branches (but do not deploy to gh-pages)
  pull_request:
jobs:
  shinylive:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      contents: write # needed for deployment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create .Renviron file
        run: |
          echo "ELEMENTS_SYSTEM_KEY=${{ secrets.ELEMENTS_SYSTEM_KEY }}" > .Renviron
      
      - name: Setup and deploy with r-shinylive
        uses: posit-dev/r-shinylive/.github/workflows/deploy-app.yaml@actions-v1
      
