# Workflow derived from https://github.com/posit-dev/r-shinylive/tree/actions-v1/examples
name: Deploy app to gh-pages
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
jobs:
  shinylive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup shinylive
        uses: posit-dev/r-shinylive/.github/actions/setup-shinylive@actions-v1
      
      - name: Create .Renviron file
        run: |
          echo "ELEMENTS_SYSTEM_KEY=${{ secrets.ELEMENTS_SYSTEM_KEY }}" > .Renviron
      
      - name: Build shinylive app
        uses: posit-dev/r-shinylive/.github/actions/build-app@actions-v1
      
      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
    permissions:
      contents: write # to deploy to Pages
      pages: write 
      id-token: write
